FROM ubuntu:24.04@sha256:a4453623f2f8319cfff65c43da9be80fe83b1a7ce689579b475867d69495b782

# ARG to control spack install (set to "false" to skip)
ARG BUILD_SPACK=false
# Build command:
# docker build -f Dockerfile.base --build-arg BUILD_SPACK=false -t shubinuh/spack-hpc:base .

LABEL maintainer="@shubinuh"

ARG uptodate_github_commit_spack__spack__develop=7868be74d84e97c00e1e4677aefab3b98dfb41af
ENV spack_commit=${uptodate_github_commit_spack__spack__develop}
ENV DEBIAN_FRONTEND=noninteractive
ENV TZ=America/Los_Angeles

# Add appropriate paths pointing to the view
ENV PATH=/opt/view/bin:/opt/spack/bin:$PATH
ENV MANPATH=/opt/view/share/man:$MANPATH
ENV PKG_CONFIG_PATH=/opt/view/lib/pkgconfig:/opt/view/lib64/pkgconfig:/opt/view/share/pkgconfig:$PKG_CONFIG_PATH
ENV CMAKE_PREFIX_PATH=/opt/view
ENV ACLOCAL_PATH=/opt/view/share/aclocal

WORKDIR /opt
COPY ./scripts /opt/scripts
# Install spack
RUN ./scripts/ubuntu/apt-install-defaults-plus-args.sh && \
    ./scripts/install-cmake-binary.sh && \
    ./scripts/set-up-spack.sh

# Tell spack to use this one without arguments
# NOTE: this has to be here, setting it earlier will kill spack
ENV SPACK_ENV=/opt/env

# Find Spack Compilers (gcc, g++, gfortran)
RUN spack compiler find

WORKDIR /code
RUN cd /code && \
    git clone --depth=1 https://github.com/mfem/mfem.git && \
    git clone --depth=1 https://github.com/dealii/dealii.git

# Create separate Spack environments for dev and prod
RUN mkdir -p /opt/env-dev /opt/env-prod
COPY ./spack.yaml /opt/env-dev/spack.yaml
COPY ./spack.prod.yaml /opt/env-prod/spack.yaml

# Install software in dev and prod envs
RUN if [ "$BUILD_SPACK" = "true" ]; then \
        cd /opt/spack && . /opt/spack/share/spack/setup-env.sh && \
        cd /opt/env-dev && \
        spack env activate . && \
        spack concretize -f && \
        spack install; \
    fi

RUN if [ "$BUILD_SPACK" = "true" ]; then \
        cd /opt/spack && . /opt/spack/share/spack/setup-env.sh && \
        cd /opt/env-prod && \
        spack env activate . && \
        spack concretize -f && \
        spack install; \
    fi

# Cleanup build artifacts (safe to ignore find errors)
RUN spack clean --all && \
    find /opt/software -type d -name build -exec rm -rf {} + 2>/dev/null || true

# ensure dev env auto-activates in login shells
RUN cd /opt/env-dev && \
    spack env activate --sh -d . >> /etc/profile.d/z10_spack_environment.sh

# Present the software install when we shell in
# Dev view: /opt/views/dev; Prod view: /opt/views/dealii-release
WORKDIR /opt/software
ENTRYPOINT ["/bin/bash", "--rcfile", "/etc/profile", "-l"]